### PR TITLE
Displaying weather

### PR DESCRIPTION
**Pull request by ziazi**
In this pull request, I made the weather display in game fragment with an icon, a description and the temperature (much more can be displayed and I would like to take the advice of the team and TAs about relevant data to do so in the last sprint). I also made the cost of querying weather and the tests less expensive so we do not have to change the key multiple times.

### CODE REVIEW

**Review by aymanelamyaghri — APPROVED** [review]
Nice feature !   But shouldn't we display  the weather on the posts also in the search Fragment? This would allow users to see the predicted weather for the game before joining it !

**Comment by ziazi** [comment]
> Nice feature ! But shouldn't we display the weather on the posts also in the search Fragment? This would allow users to see the predicted weather for the game before joining it !

You are totally right and this should be done !
However, in this sprint, post UI is being changed and I only have access now to the old UI. So I can't really work on them to display the weather in this sprint.

**Comment by DerouichAbdessalam** [comment]
Good job man, just a question, when we discussed the implementation you said that the queries were a bit  expensive, were you able to fix that?

**Comment by ziazi** [comment]
> Good job man, just a question, when we discussed the implementation you said that the queries were a bit expensive, were you able to fix that?

Exactly, Actually, past queries cost much more than forecast, forecast cost is 1 whatever you queried 1 or 15days. So to fix that, I modified the url to request strictly one day and only get the specific hour I needed. Moreover, I modified tests to store redundant queries in fields and use them multiple times.

**Pull request merged**
