### PR TITLE
D bfilters

### PR DESCRIPTION
**Pull request by DerouichAbdessalam**
In this PR, I added the schedule database in FireStore, my main work consisted of  adding the API to manipulate it allowing for future synchronization between the in app local schedule and the database. I also added some filtering methods for the posts database to facilitate posts database manipulation.

### CODE REVIEW

**Review by ktotam1 — COMMENTED** [review]
looks good to me

**Review by ziazi — APPROVED** [review]
Great work  :-)
I have a question though, should TimeStamp::isBefore really take into account the seconds ? it's too accurate for me and complexifies the code a little bit, but good job on handling that !

**Comment by DerouichAbdessalam** [comment]
> Great work :-) I have a question though, should TimeStamp::isBefore really take into account the seconds ? it's too accurate for me and complexifies the code a little bit, but good job on handling that !

Yeah, I was actually wondering if i should keep that or not. i thought that more precision is always better but the other way works perfectly too.

**Review by hamzaremmal — APPROVED** [review]
Good work :-) Lets merge it

**Pull request merged**
