### PR TITLE
Added screen for detailed informations of a game  and added abilty to see  schedule for next and previous weeks

### PR DESCRIPTION
**Pull request by aymanelamyaghri**
In this PR, I added the functionality to look  at previous and next weeks in the schedule of a user,(still not connected to the DB), I also added the abilty to click on a game in the schedule  and take a look at its detailed informations. Finally, I  added the ability to rate players that  the user played with in the same game, the list of users shows up with the detailed informations about the game.

### CODE REVIEW

**Review by Adam-GitHub0 — COMMENTED** [review]
Hello, wouldn't it be a good idea to add an attribute (in Game Fragment)  for the creator of the announcement and display it on the screen ,so that we know who did create the announcement  ?

**Comment by aymanelamyaghri** [comment]
> Hello, wouldn't it be a good idea to add an attribute (in Game Fragment) for the creator of the announcement and display it on the screen ,so that we know who did create the announcement ?

Yes, that would be nice , I will add it when we connect the schedule to the DataBase in next sprints!

**Comment by Adam-GitHub0** [comment]
Okay great ! Really nice work by the way !

**Comment by Adam-GitHub0** [comment]
Okay great ! Very nice work by the way !

**Review by Adam-GitHub0 — APPROVED** [review]

**Pull request merged**
