### PR TITLE
Adding top games fragment

### LINKED ISSUE #162: Design  in Figma  a fragment  containing the Top 3 most played sports of the month

### LINKED ISSUE #163: Implement the design of the Top3 Sports from Figma to Android studio

### LINKED ISSUE #164: make the Top3 Sports Fragments interactive by adding buttons and functionalities

### LINKED ISSUE #165: Add the functionality of switching  from  a Top3 Sports to its related posts

### PR DESCRIPTION
**Pull request by aymanelamyaghri**
In this PR, I added a fragment where we can See the  top trending sports for the current Month , We can also see the number of games (posts)  of the sport and see related posts by clicking on the image of the trending sport. This PR fixes some previous tests that were related to some problems with the CI. I also added some documentation and comments on previous classes and tests that I have written in previous PRs.

### CODE REVIEW

**Review by ziazi — DISMISSED** [review]
Thank you for the pull request and nice job!
The code climate seems nevertheless unhappy about some basic stuff like duplication and "complexe"logical expression but this can be fixed later. 👌🏻

**Review by ziazi — COMMENTED** [review]
Great work!
 However it looks like you are using dummy data for the number of post .

**Review by Adam-GitHub0 — APPROVED** [review]
I noticed on the top Sports fragment you are  displaying the number of posts ,isn't it better to  
 show the number of games already played instead ? Otherwise , really great work !

**Comment by aymanelamyaghri** [comment]
> Great work! However it looks like you are using dummy data for the number of post .

Yes !  This will be fixed in the next Sprint, I just prepared the interface  now to communicate with the DataBase where I used dummy data. I also talked to Abdessalam to prepare the methos to fetch informations from the DataBase. This will be done in the next Sprint !

**Comment by aymanelamyaghri** [comment]
> I noticed on the top Sports fragment you are displaying the number of posts ,isn't it better to show the number of games already played instead ? Otherwise , really great work !

That could be a good idea, but I thought that the main reason of showing this information is to show the user that it is a trending sport and the number of posts related to it is quite sufficient. But we can discuss this with the team !

**Pull request merged**
