### PR TITLE
Draw path and changes

### PR DESCRIPTION
**Pull request by Adam-GitHub0**
This pull request does 3 major tasks :
-We can now see  a path between our current position  and the selected field.
-We can edit the default radius for the choose location option ( which shows the closest fields to a certain position ).
-When we click on the location tab , we directly have the closest fields to our current position(This is not the default option for test purposes , but its implemented).

### CODE REVIEW

**Review by DerouichAbdessalam — COMMENTED** [review]
good work this sprint. I just want to point out that from a user standpoint, we might be at the point where adding anything to the map is overkill and it would be better to start working on some other aspects of the app instead

**Comment by Adam-GitHub0** [comment]
> good work this sprint. I just want to point out that from a user standpoint, we might be at the point where adding anything to the map is overkill and it would be better to start working on some other aspects of the app instead

Yes  you 're right , I think it's enough for the map for now !

**Comment by DerouichAbdessalam** [comment]
> > good work this sprint. I just want to point out that from a user standpoint, we might be at the point where adding anything to the map is overkill and it would be better to start working on some other aspects of the app instead
> 
> Yes you 're right , I think it's enough for the map for now !

**Review by DerouichAbdessalam — APPROVED** [review]
Nothing to add on the map for now that's for sure, just for the future maybe adding a search bar for the locations would help. but again for the fuuuuture

**Comment by Adam-GitHub0** [comment]
> Nothing to add on the map for now that's for sure, just for the future maybe adding a search bar for the locations would help. but again for the fuuuuture

I agree , Great idea !

**Pull request merged**
