### PR TITLE
Chat UI fix

### LINKED ISSUE #158: as a user I want to be able to se chat with my friends through the app to fixate specific arrangements

### LINKED ISSUE #204: make the chat fragment more appealing

### PR DESCRIPTION
**Pull request by DerouichAbdessalam**
In this PR we fix the UI for chats, a total rework of the chat layouts and their components, i also refactored main UI elements to enable future synchronization between all UI elements in the last sprint in order to give the app a cohesive feel

### CODE REVIEW

**Comment by ziazi** [comment]
Nice job with the UI!
However, it looks to me that your work is still not consistent in all the App

**Comment by DerouichAbdessalam** [comment]
> Nice job with the UI! However, it looks to me that your work is still not consistent in all the App

yeah, as i mentioned in the PR, next sprint will be dedicated to making the wole app feel (UI) coherent

**Review by Adam-GitHub0 — COMMENTED** [review]
nice work on the UI, it's a great improvement from what we had before, just wondering why some database code is still commented ?

**Review by hamzaremmal — APPROVED** [review]
Good job there ;-)

**Comment by hamzaremmal** [comment]
@cs306-versus/dev Should we get this merge ?

**Comment by ziazi** [comment]
> > Nice job with the UI! However, it looks to me that your work is still not consistent in all the App
> 
> yeah, as i mentioned in the PR, next sprint will be dedicated to making the wole app feel (UI) coherent

Alright, just making sure we're on track for the last sprint, more of a little remainder ;)
Awesome job! keep it up buddy 👍🏻

**Comment by aymanelamyaghri** [comment]
Nice implementation! However  , I noticed in the XML code of the ChatFragment that there are some unused views for the email  and the date of the message? Should we delete them?

**Comment by DerouichAbdessalam** [comment]
> @cs306-versus/dev Should we get this merge ?
> Yeah I've just merged it !

**Comment by DerouichAbdessalam** [comment]
> Nice implementation! However  , I noticed in the XML code of the ChatFragment that there are some unused views for the email  and the date of the message? Should we delete them?

Actually those are a part of some preparation i did for next sprint where i'll be adding those fields to the overall chat view

**Pull request merged**
