### PR TITLE
Chat activity

### LINKED ISSUE #159: add messaging activity

### LINKED ISSUE #160: add synchronization with chat database

### LINKED ISSUE #161: Offer more informations about the locations such as opening hours ...

### PR DESCRIPTION
**Pull request by DerouichAbdessalam**
in this PR, we add 2 screens, one to view chats with other users and another to checkout a specific chat enabling the user to send and receive messages

### CODE REVIEW

**Review by aymanelamyaghri — COMMENTED** [review]
Good work on the chatting interface, however the global chat interface needs some work , it looks quite simplistic for the final version of the app.

**Comment by DerouichAbdessalam** [comment]
> Good work on the chatting interface, however the global chat interface needs some work , it looks quite simplistic for the final version of the app.

Yeah i tried to get the necessary going so that i can first get a correct chat functionality without added complexity from the UI part but i'll make sure to get a cool design for next sprint

**Review by Adam-GitHub0 — COMMENTED** [review]
Wouldn't it be a good idea to have an additional fragment  for group chats ( in addition to the private chats)? And also could we  have a search bar for the user to look for specific chats instead of scrolling through all of them? 
Apart from this , very good work !

**Comment by DerouichAbdessalam** [comment]
> Wouldn't it be a good idea to have an additional fragment for group chats ( in addition to the private chats)? And also could we have a search bar for the user to look for specific chats instead of scrolling through all of them? Apart from this , very good work !

yeah ! i thought about the groups feature and i think 'll leave it for the last sprint, for the next one i'll focus on getting a polished version of the app

**Review by aymanelamyaghri — APPROVED** [review]
Also , I noticed that the link to the DB has not been completed, just make sure to do that next Sprint

**Comment by DerouichAbdessalam** [comment]
> Also , I noticed that the link to the DB has not been completed, just make sure to do that next Sprint

yeah don't worry, i already put it in my tasks for next sprint

**Pull request merged**
