### PR TITLE
Adding Sport Equipments Fragment

### LINKED ISSUE #254: Design on figma the fragment of selling/renting sports equipments

### LINKED ISSUE #255: Implement the  design  of the sports equipments on android studio

### LINKED ISSUE #256: Add functionalities (buttons etc..) to the sports equipments fragment

### LINKED ISSUE #257: Add the ability to filter the sports equipments posts based on the sport

### LINKED ISSUE #261: Fix Bug related to Schedule

### LINKED ISSUE #262: Implement  on figma the design of the contact  info fragments

### LINKED ISSUE #263: Implement the contact info fragment on android studio

### PR DESCRIPTION
**Pull request by aymanelamyaghri**
In this PR, I added the fragment to buy/rent Sport Equipments, I also added the ability to filter the posts based on the keywords in the title and description , and added a fragment that contains the contact informations of the owner of the post , I also fixed a bug related to the schedule dates.

### CODE REVIEW

**Review by Adam-GitHub0 — COMMENTED** [review]
Nice implementation of the SportsEquipments Fragment, but I can see that there is no way to create a post to sell or loan the sports equipements . 
Also it is not connected to the DataBase !

**Comment by aymanelamyaghri** [comment]
> Nice implementation of the SportsEquipments Fragment, but I can see that there is no way to create a post to sell or loan the sports equipements . Also it is not connected to the DataBase !

Yeah , the creation of post will be done in the next Sprint just before connecting to the DB, it should be all fine by the end of the next Sprint.

**Review by Adam-GitHub0 — APPROVED** [review]
I also see that  you added a contructor  for a  dummyUser , is It necessary?

**Comment by aymanelamyaghri** [comment]
> I also see that you added a contructor for a dummyUser , is It necessary?

I Added  the contructor in order to facilitate   the creation of dummy posts for this Sprint, when the users are connected to the DB , it should be easy to replace that !

**Pull request merged**
