### PR TITLE
Implement User in Versus

### LINKED ISSUE #55: Create class for User

### PR DESCRIPTION
**Pull request by hamzaremmal**
This PR introduces the notion of User in Versus. 

We still need to link it to the authentication process and fetch informations from the DataBase (this will be done in a separate PRs).

### CODE REVIEW

**Review by aymanelamyaghri — COMMENTED** [review]
Concerning the VersusUser implementation, Wouldn't be better to have a Map of ratings for each sport rather than one rating for every sport?

**Comment by hamzaremmal** [comment]
> Concerning the VersusUser implementation, Wouldn't be better to have a Map of ratings for each sport rather than one rating for every sport?

That's not the decision we took. Also, it doesn't make sense to have a rating per sport. This rating is a global one, we can have for example the list of ratings that led to the global one; we can add the sport there or maybe event a link to the game (post)

**Comment by aymanelamyaghri** [comment]
I think It does make sense to have a rating per sport, If someone is really good at sport1, but want to try for the first time another sport, it's not logical for him to have a good  rating at all sports, separating the ratings would give more credibility to them, you could alsoadd a general rating for the user , that could be nice too.

**Comment by hamzaremmal** [comment]
> I think It does make sense to have a rating per sport, If someone is really good at sport1, but want to try for the first time another sport, it's not logical for him to have a good rating at all sports, separating the ratings would give more credibility to them, you could alsoadd a general rating for the user , that could be nice too.

Ok, but we can agree that the same problem emerges when someone signs up to use the app. Then what grading should they have. Also, the purpose of the rating was to add the information about how the player did during a game (the sport is not important here). One might have a high rating, which reflect his punctuality, sportsmanship / fair-play, and so on. All of these lead to have one global rating and not multiple ones.

**Comment by hamzaremmal** [comment]
Also, one can take as an example chess, where we have different [Elo (rating)](https://www.chess.com/fr/terms/systeme-elo-echecs) depending on the type of the game (Bltiz, Classic, ...). This system reflects the level of the person in the same game (Chess) but in different modes, not different games.

**Comment by aymanelamyaghri** [comment]
Yeah, as I said before having a general rating is for sure a good idea, but I think specific ratings could be useful too , for now it is okay, we can discuss it  with the rest of the team later.

**Comment by aymanelamyaghri** [comment]
> Also, one can take as an example chess, where we have different [Elo (rating)](https://www.chess.com/fr/terms/systeme-elo-echecs) depending on the type of the game (Bltiz, Classic, ...). This system reflects the level of the person in the same game (Chess) but in different modes, not different games.

Well for our app , we have different sports and not modes, so maybe a rating for each sport is valuable, for someone who is only interested in finding people really good at BasketBall , why should he be influenced by multiple football ratings of someone? You mentionned earlier  a possibility to have  links to previous games that he could see in order to have details of the global rating , but a specific rating to the sport that interest him may save him some time.

**Comment by hamzaremmal** [comment]
> > Also, one can take as an example chess, where we have different [Elo (rating)](https://www.chess.com/fr/terms/systeme-elo-echecs) depending on the type of the game (Bltiz, Classic, ...). This system reflects the level of the person in the same game (Chess) but in different modes, not different games.
> 
> Well for our app , we have different sports and not modes, so maybe a rating for each sport is valuable, for someone who is only interested in finding people really good at BasketBall , why should he be influenced by multiple football ratings of someone? You mentionned earlier a possibility to have links to previous games that he could see in order to have details of the global rating , but a specific rating to the sport that interest him may save him some time.

One can have a graph; like the [Github Contribution Graph (below)](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/viewing-contributions-on-your-profile#activity-overview), where we can see the games one have played before and their percentage (how they contributed to the overall project). Lets not focus on this for now and see how we can deal with that later.

github_contribution_graph

**Comment by aymanelamyaghri** [comment]
Ok, we'll discuss it with the team later.Otherwise , the PR is great, the rest looks good to me.

**Review by aymanelamyaghri — APPROVED** [review]

**Pull request merged**
