### PR TITLE
 Choose location when creating a post

### PR DESCRIPTION
**Pull request by Adam-GitHub0**
When creating a post , you can now choose the location of the game .

### CODE REVIEW

**Comment by aymanelamyaghri** [comment]
Nice feature ! but im wondering why did you choose to show a search bar instead of the whole map ? like in the location fragment?

**Comment by aymanelamyaghri** [comment]
Nice feature ! but im wondering why did you choose to show a search bar instead of the whole map ? like in the location fragment?

**Comment by Adam-GitHub0** [comment]
> Nice feature ! but im wondering why did you choose to show a search bar instead of the whole map ? like in the location fragment?

Thanks, I did this because i think it's easier to search a location by name than looking in the map, and if he wants to look in the map , he can always go to the location fragment and find the closest fields to his location !

**Comment by aymanelamyaghri** [comment]
Also,Why did you implement the onActivityResult method in the SearchFragment class , and not  in the LocationPickerDialog?

**Comment by Adam-GitHub0** [comment]
> Also,Why did you implement the onActivityResult method in the SearchFragment class , and not in the LocationPickerDialog?

Great remark , I did this because the "onActivityResult" method will be called in the hosting Activity or Fragment(which is the search Bar fragment) but not in the LocationPickerDialogFragment itself, which will lead the searchBar to not come back to the creation of the post .

**Review by aymanelamyaghri — APPROVED** [review]

**Pull request merged**
