### PR TITLE
Linking the Posts Cache to the App

### LINKED ISSUE #223: As a user, I want to know when I'm offline but still see my cached posts

### LINKED ISSUE #300: Link the cache to the main activity

### PR DESCRIPTION
**Pull request by ziazi**
In this PR, I linked the cache to the app and we can access posts offline. Every post fetched from firebase or created is stored in the local Room database. When the device is offline, the app fetches the post from the cache instead of the firebase.

### CODE REVIEW

**Comment by aymanelamyaghri** [comment]
Nice work , but is the User Fragment cached also? I can see that even without   Wifi , we can still see the users informations?

**Review by hamzaremmal — APPROVED** [review]
Finally the offline mate ;-)

**Review by aymanelamyaghri — APPROVED** [review]

**Review by Adam-GitHub0 — COMMENTED** [review]
Good work ! I see what you did there !Now even if we 're offline , we can check the posts , but can we also see the user profile ?

**Comment by ziazi** [comment]
> Finally the offline mate ;-)

Yeah it's time it was linked 😂

**Comment by ziazi** [comment]
> Nice work , but is the User Fragment cached also? I can see that even without Wifi , we can still see the users informations?

Yes the user is still  available even when there is no connection GIVEN that the internet interruption occurred after connecting to Firestore. While the posts are progressively stored locally and permanently and retrieved as soon as the internet is not available without waiting for a timeout or something.
That was a good catch mate ;)

**Comment by ziazi** [comment]
> Good work ! I see what you did there !Now even if we 're offline , we can check the posts !

Finally :)

**Comment by aymanelamyaghri** [comment]
> > Good work ! I see what you did there !Now even if we 're offline , we can check the posts !
> 
> Finally :)

Oh okay ! Nice work by the way

**Pull request merged**
